load("//helpers:ios.bzl", "swiftui_plugin")

swiftui_plugin(
    name = "ProfilerPlugin",
    deps = [
      "@swiftpkg_swiftflipper//:SwiftFlipper",
      "//devtools/plugin/swiftui:PlayerUIDevtoolsSwiftUIPlugins",
      "//devtools/plugins/profiler/ios:PlayerUIDevtoolsBaseProfilerDevtoolsPlugin"
      ],
    test_deps = []
)
