disabled_rules:
  - multiple_closures_with_trailing_closure # This rule conflicts with Xcode default styles...
  - todo
line_length:
    warning: 160
    ignores_comments: true
identifier_name:
  excluded:
    - ui_object
    - ui_action
    - ui_object_detail
    - page_experience
    - screen_object_state
    - render_time
    - id
    - scope_area
    - ecs_version
    - segment_type
    - ui_access_point
    - object_detail
