packages:
  - cli
  - docs/*
  - devtools/types/core
  - devtools/plugin/core
  - devtools/plugin/react
  - devtools/plugins/basic/core
  - devtools/plugins/basic/react
  - devtools/plugins/profiler/core
  - devtools/plugins/profiler/react
  - devtools/messenger/core
  - devtools/utils/ios/Resources/core
  - mocks/

onlyBuiltDependencies:
  - esbuild
  - husky
