packages:
  - cli
  - docs/*
  - devtools/client
  - devtools/flipper-plugin
  - devtools/mcp
  - devtools/plugin/core
  - devtools/plugin/react
  - devtools/plugins/basic/content
  - devtools/plugins/basic/core
  - devtools/plugins/basic/react
  - devtools/messenger/core
  - devtools/types/core
  - devtools/utils/core
  - devtools/utils/ios/Resources/core
  - mocks/

onlyBuiltDependencies:
  - esbuild
  - husky
