load("//helpers:ios.bzl", "swiftui_plugin")

swiftui_plugin(
    name = "BasicPlugin",
    deps = [
      "@swiftpkg_swiftflipper//:SwiftFlipper",
      "//devtools/plugin/swiftui:PlayerUIDevtoolsSwiftUIPlugin",
      "//devtools/plugins/basic/ios:PlayerUIDevtoolsBaseBasicDevtoolsPlugin"
      ],
    test_deps = []
)