load("//helpers:ios.bzl", "swiftui_plugin")

swiftui_plugin(
    name = "BasicPlugin",
    deps = [
      "@swiftpkg_swiftflipper//:SwiftFlipper",
      "//devtools/plugins/basic/ios:PlayerUIDevToolsBaseBasicDevtoolsPlugin",
      ],
    test_deps = []
)