# Messenger iOS library
load("//helpers:ios.bzl", "ios_library")

# iOS library for the Messenger
ios_library(
    name = "Types",
    resources = ["//devtools/types/core:core_native_bundle"],
    deps = [
        "//devtools/utils/ios:PlayerUIDevToolsUtils",
    ]
)
