# Messenger iOS library
load("//helpers:ios.bzl", "ios_library")

# iOS library for the Messenger
ios_library(
    name = "Types",
    deps = [
        "//devtools/utils/ios:PlayerUIDevtoolsUtils",
    ]
)
