load("//helpers:ios.bzl", "ios_library")

ios_library(
    name = "BaseBasicDevtoolsPlugin",
    resources = ["//devtools/plugins/basic/core:core_native_bundle"],
    deps = [
      "//devtools/plugin/ios:PlayerUIDevtoolsPlugins",
      "//devtools/utils/swiftui:PlayerUIDevtoolsUtilsSwiftUI"
    ],
)
