load("//helpers:ios.bzl", "ios_library")

ios_library(
    name = "BasicCoreWrapper",
    resources = ["//devtools/plugins/basic/core:core_native_bundle"],
    deps = [
      "//devtools/plugin/ios:PlayerUIDevToolsPlugins"
    ],
)