version: 2.1

executors:
  base:
    docker:
      - image: docker.io/playerui/bazel-docker
    working_directory: ~/devtools
    resource_class: large
    environment:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"

jobs:
  checkLabels:
    executor: base
    steps:
      - attach_workspace:
          at: ~/devtools
      - run:
          name: Check SemVer label
          command: yarn auto pr-check --url $CIRCLE_BUILD_URL

  test:
    executor: base
    steps:
      - attach_workspace:
          at: ~/devtools
      - run:
          name: Test
          command: bazel test //...

  # TODO: Add release phase

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkLabels:
          context:
            - Publish

      - test: