load("@npm//:defs.bzl", "npm_link_all_packages")
load("@rules_player//player:defs.bzl", create_base_dsl_config = "create_base_config", compile_mocks = "compile_mocks")

npm_link_all_packages(name = "node_modules")

create_base_dsl_config(
    name = "dsl_config",
    presets = [
        "//:node_modules/@player-ui/reference-assets-cli-preset",
    ],
)

# TODO: Add all sub-folders here AND in the package.json file
MOCK_DIRS = [
    "action",
    "collection",
    "info",
    "input",
    "text",
]

compile_mocks(
    name = "mocks",
    mock_dirs = MOCK_DIRS,
    dsl_config = ":dsl_config",
    data = [
        "//:node_modules/@player-ui/reference-assets-cli-preset",
        "//:node_modules/@player-ui/reference-assets-plugin-components",
    ]
)