# Messenger iOS library
load("//helpers:ios.bzl", "ios_library")

# iOS library for the Messenger
ios_library(
    name = "Messenger",
    resources = ["//devtools/messenger/core:core_native_bundle"],
    deps = [
        "//devtools/types/ios:PlayerUIDevToolsTypes",
        "//devtools/utils/ios:PlayerUIDevToolsUtils",
    ],
)
