load("//helpers:ios.bzl", "swiftui_plugin")

swiftui_plugin(
    name = "UtilsSwiftUI",
    deps = [
        "@swiftpkg_playerui_swift_package//:PlayerUILogger",
    ],
    test_deps = [
        "@swiftpkg_playerui_swift_package//:PlayerUITestUtilitiesCore",
    ]
)

