load("//helpers:ios.bzl", "ios_library")

ios_library(
    name = "ProfilerDevtoolsPlugin",
    resources = ["//devtools/plugins/profiler/core:core_native_bundle"],
    deps = [
        "//devtools/types/ios:PlayerUIDevToolsTypes",
        "//devtools/utils/ios:PlayerUIDevToolsUtils",
    ],
)
