load("//helpers:ios.bzl", "ios_library")

ios_library(
    name = "Utils",
    # Do not include this core bundle in the released Package. This is just for testing.
    resources = ["//devtools/utils/ios/Resources/core:core_native_bundle"],
)
